<?php
/**
 * nToklo
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Ntoklo
 * @package    Ntoklo_Recommendations
 * @copyright  Copyright (c) 2013 nToklo (http://ntoklo.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     nToklo
 */
?>
<!-- nToklo Start -->
<script type="text/javascript">
    //<![CDATA[
    var _ntoklo_key          = "<?php echo $this->getNtokloApiKey(); ?>";
    var _ntoklo_debug        = <?php echo $this->isNtokloDebugActive(); ?>;
    var _ntoklo_host         = "<?php echo $this->getNtokloApiServiceUrl(); ?>";
    var _ntoklo_event_rate   = "<?php echo Ntoklo_Recommendations_Helper_Data::PAGE_CATEGORY_RATE; ?>";
    var _ntoklo_event_review = "<?php echo Ntoklo_Recommendations_Helper_Data::PAGE_CATEGORY_REVIEW; ?>";
    Event.observe(window, 'load', function(){
        window.universal_variable = window.universal_variable || {};
        var _ntoklo = new Ntoklo("<?php echo $this->getNtokloScriptUrl(); ?>", (<?php echo $this->getJsonUniversalVariable(); ?>));
        _ntoklo.loadEvent();
    });
    //]]>
</script>
<!-- nToklo End -->