<?php
/**
 * nToklo
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Ntoklo
 * @package    Ntoklo_Recommendations
 * @copyright  Copyright (c) 2013 nToklo (http://ntoklo.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     nToklo
 */
?>

<?php if (($_products = $this->getItems()) && count($_products)): 
$getTrackerId = Mage::helper('ntoklo_recommendations')->getWidgetType();

?>
    <!-- nToklo Chart -->
    <div class="widget-ntoklo-container clearfix" style="clear:both">
        <?php $_columnCount = $this->getColumnCount(); ?>
        <div class="nt_wrapper nt_grid nt_orange nt_<?php echo $_columnCount ?>_column">
            <p class="nt_header"><?php echo $this->getHeader() ?></p>
            <div class="nt_widget clearfix">
                <?php $i=0; foreach ($_products as $_product): ?>
                    <?php if ($i++%$_columnCount==0): ?>
                        <div class="nt_row clearfix">
                    <?php endif ?>
                            <div class="nt_item_wrap" style="width:<?php echo (100 / $_columnCount) ?>%">
                                <div class="nt_img_wrap">
                                    <a href="<?php echo Mage::getUrl($_product->getUrlPath(), array('_query'=>array($getTrackerId =>  Mage::helper('ntoklo_recommendations')->getTrackerId())))?>" class="ntoklo_conversion"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(100) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"></a>
                                </div>
                                <span class="nt_product_title"><?php echo $this->htmlEscape($_product->getName()) ?></span>
                                <span class="nt_product_price"><?php echo Mage::helper('core')->currency($_product->getPrice()); ?></span>
                                <a href="<?php echo Mage::getUrl($_product->getUrlPath(), array('_query'=>array($getTrackerId =>  Mage::helper('ntoklo_recommendations')->getTrackerId())))?>" class="nt_btn">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="10.853px" height="11.229px" viewBox="0 0 10.853 11.229" enable-background="new 0 0 10.853 11.229" xml:space="preserve">
                                            <g>
                                                <path fill="#fff" d="M8.825,6.164l-4.367,4.361c-0.154,0.154-0.375,0.248-0.603,0.248c-0.229,0-0.449-0.094-0.604-0.248l-0.509-0.502C2.589,9.862,2.495,9.64,2.495,9.413c0-0.229,0.094-0.449,0.248-0.604l3.255-3.255L2.743,2.305c-0.154-0.16-0.248-0.382-0.248-0.609s0.094-0.449,0.248-0.603L3.252,0.59C3.406,0.43,3.627,0.336,3.855,0.336c0.228,0,0.448,0.094,0.603,0.254l4.367,4.361c0.154,0.153,0.248,0.375,0.248,0.603S8.979,6.003,8.825,6.164z"/>
                                            </g>
                                    </svg>
                                </a>
                            </div>
                    <?php if ($i%$_columnCount==0 || $i==count($_products)): ?>
                        </div>
                    <?php endif ?>
                <?php endforeach; ?>
            </div>
           
        </div>
    </div>
    <!-- //END nToklo Chart -->
<?php endif; ?>
