<?php
/**
 * nToklo
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Ntoklo
 * @package    Ntoklo_Recommendations
 * @copyright  Copyright (c) 2013 nToklo (http://ntoklo.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     nToklo
 */
?>

<?php if (($_products = $this->getItems()) && count($_products)):
$getTrackerId = Mage::helper('ntoklo_recommendations')->getWidgetType();
?>
    <!-- nToklo Chart -->
    <div class="widget-ntoklo-container clearfix" style="clear:both">
        <div class="nt_wrapper nt_column nt_green nt_img_above">
            <p class="nt_header"><?php echo $this->getHeader() ?></p>
            <ul class="nt_widget">
                <?php $i=0; foreach ($_products as $_item):?>
                    <li>
                        <div class="nt_item_wrap">
                            <div class="nt_img_wrap">
                                <a href="<?php echo Mage::getUrl($_item->getUrlPath(), array('_query'=>array($getTrackerId =>  Mage::helper('ntoklo_recommendations')->getTrackerId())))?>" class="ntoklo_conversion"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(100) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>"></a>
                            </div>
                            <div class="nt_info_wrap">
                                <span class="nt_product_title"><?php echo $this->htmlEscape($_item->getName()) ?></span>
                                <span class="nt_product_price"><?php echo Mage::helper('core')->currency($_item->getPrice()); ?></span>
                                <a href="<?php echo Mage::getUrl($_item->getUrlPath(), array('_query'=>array($getTrackerId =>  Mage::helper('ntoklo_recommendations')->getTrackerId())))?>" class="ntoklo_conversion nt_btn"><?php echo $this->__('More details') ?></a>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
            
        </div>
    </div>
    <!-- //END nToklo Chart -->
<?php endif ?>
