<?php
/**
 * nToklo
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Ntoklo
 * @package    Ntoklo_Recommendations
 * @copyright  Copyright (c) 2013 nToklo (http://ntoklo.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     nToklo
 */
?>

<?php if(count($this->getItems())): ?>
    <!-- nToklo Chart -->
    <div class="block widget-ntoklo-container">
        <div class="block-title">
            <strong><span><?php echo $this->getHeader() ?></span></strong>
        </div>
        <div class="block-content ntoklo-vertical">
            <ol class="mini-products-list <?php if($this->isChart()) echo 'chart';?>" id="block-ntoklo-chart">
                <?php foreach($this->getItems() as $_item): ?>
                    <li class="item">
                        <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                            <div class="product">
                                <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image ntoklo_conversion"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                                <div class="product-details">
                                    <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" class="ntoklo_conversion"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                                    <?php echo $this->getPriceHtml($_item, true, '-ntoklo-chart') ?>
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist ntoklo_conversion"><?php echo $this->__('Add to Wishlist') ?></a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach ?>
            </ol>
            <script type="text/javascript">decorateList('block-ntoklo-chart', 'none-recursive')</script>
        </div>
    </div>
    <!-- //END nToklo Chart -->
<?php endif ?>